pre_install() {
    getent group crypto >/dev/null || groupadd -r crypto
    getent passwd bitcoin >/dev/null || useradd -r -U -K UMASK=0077 -G crypto -b /blockchain -d /blockchain/bitcoin -s /usr/bin/nologin -c "Bitcoin core" bitcoin
}

post_install() {
    chown -R bitcoin:bitcoin /etc/bitcoin
    systemctl daemon-reload
}

pre_upgrade() {
    systemctl stop bitcoind.service
}

pre_remove() {
    systemctl stop bitcoind.service
    systemctl disable bitcoind.service
}
